CREATE DATABASE IF NOT EXISTS dostavim;
USE dostavim;

CREATE TABLE CLIENT
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT
);
CREATE TABLE LEG
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    START_VERTEX INT(11) NOT NULL,
    END_VERTEX INT(11) NOT NULL,
    MAX_WEIGHT DOUBLE NOT NULL,
    LEG_TYPE ENUM('TRAIN', 'AVIA') NOT NULL,
    BASE_PRICE DOUBLE NOT NULL,
    SEND_TIME INT(11) DEFAULT '20' NOT NULL
);
CREATE TABLE ORDERS
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    START_DATE DATETIME NOT NULL,
    CLIENT_ID INT(11) NOT NULL,
    START_VERTEX INT(11) NOT NULL,
    END_VERTEX INT(11) NOT NULL,
    ORDER_TYPE ENUM('TIME', 'PRICE') NOT NULL,
    RECEIVER_ID INT(11) DEFAULT '1' NOT NULL,
    ORDER_STATUS ENUM('WAIT_CREATE', 'WAIT_CHANGE', 'MOVING', 'READY', 'COMPLETED') DEFAULT 'WAIT_CREATE' NOT NULL,
    CONSTRAINT ORDER_CLIENT_ID_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID),
    CONSTRAINT ORDERS_CLIENT_ID_fk FOREIGN KEY (RECEIVER_ID) REFERENCES CLIENT (ID)
);
CREATE INDEX ORDERS_CLIENT_ID_fk ON ORDERS (RECEIVER_ID);
CREATE INDEX ORDER_CLIENT_ID_fk ON ORDERS (CLIENT_ID);
CREATE TABLE PRODUCT
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    WEIGHT DOUBLE NOT NULL,
    PRICE DOUBLE,
    ORDER_ID INT(11) NOT NULL,
    CONSTRAINT PRODUCT_ORDER_ID_fk FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);
CREATE INDEX PRODUCT_ORDER_ID_fk ON PRODUCT (ORDER_ID);
CREATE TABLE ROUTE
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ORDER_ID INT(11) NOT NULL,
    CURRENT_ROUTE_LEG_ID INT(11),
    CONSTRAINT ROUTE_ORDERS_ID_fk FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);
CREATE INDEX ROUTE_ORDERS_ID_fk ON ROUTE (ORDER_ID);
CREATE TABLE ROUTE_LEG
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LEG_ID INT(11) NOT NULL,
    ROUTE_ID INT(11) NOT NULL,
    START_TIME DATETIME,
    END_TIME DATETIME,
    CONSTRAINT ROUTE_LEG_LEG_ID_fk FOREIGN KEY (LEG_ID) REFERENCES LEG (ID),
    CONSTRAINT ROUTE_LEG_ROUTE_ID_fk FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE (ID)
);
CREATE INDEX ROUTE_LEG_LEG_ID_fk ON ROUTE_LEG (LEG_ID);
CREATE INDEX ROUTE_LEG_ROUTE_ID_fk ON ROUTE_LEG (ROUTE_ID);
